name: "\U0001F41B Bug Report"
description: Report a bug or unexpected behavior in LibAnimate
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Call `lib:Animate(frame, "fadeIn", { ... })`
        2. Immediately call `lib:Stop(frame)`
        3. Observe error in chat
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include any error messages.
    validations:
      required: true

  - type: dropdown
    id: wow-version
    attributes:
      label: WoW Version
      options:
        - Retail
        - MoP Classic
        - TBC Anniversary
    validations:
      required: true

  - type: input
    id: lib-version
    attributes:
      label: LibAnimate Version
      description: Version number from the TOC or "latest".
      placeholder: "3.5.4"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Error logs, screenshots, relevant addon list, or anything else.
    validations:
      required: false
