name: "\U00002728 Feature Request"
description: Suggest a new feature or improvement for LibAnimate
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is it needed?
      placeholder: I want to animate X but there is no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or API you would like.
      placeholder: |
        A new `lib:FooBar(frame, ...)` method that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you have considered.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Examples, references, mockups, or anything else.
    validations:
      required: false
